# Numpy

NumPy és la base de Pandas i molts altres paquets. El que fa que NumPy sigui un paquet tan increïble és el seu tipus de dades (ndarray). ndarray significa matriu n-dimensional, que bàsicament sembla una llista de Python. Tanmateix, és molt més ràpid que una llista normal de Python. Una llista de Python pot contenir diferents tipus de tipus de dades, com ara nombres enters, cadenes, booleans, vertader, fals i fins i tot llistes. D'altra banda, les matrius NumPy només poden contenir un tipus de dades i, per tant, no han de comprovar el tipus de dades per a cada element de la matriu quan fa els càlculs. Aquesta característica fa que NumPy sigui una gran eina per a la investigació i els projectes de ciències de dades.

Aquí teniu una col·lecció de petits exercicis que us poden ajudar a entendre millor les moltes funcionalitats de Numpy. Alguns d'ells s'han cobert a les parts de la teoria, d'altres no. En aquest cas, trobareu alguns consells sobre els mètodes que feu servir, però hauríeu de navegar per la documentació de NumPy per entendre com utilitzar aquests mètodes exactament.

Podeu trobar la documentació de NumPy a [https://docs.scipy.org/doc/numpy/]()

## Numpy Arrays

#### 1. Importeu el paquet numpy amb el nom `np`  ( Import the numpy package as `np`)


In [1]:
import numpy as np

#### 2. Imprimeix la versió numpy (Print the numpy version)

In [2]:
import numpy as np
dir(np) 

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

#### 3. Creeu una array 1D de 0 a 9 (Create a 1D array of numbers from 0 to 9)

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [3]:
array = list(range(10))

print(array)

array1 = np.arange(10)

print(array1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


#### 4. Creeu una matriu unidimensional de 10 zeros (Create a 1D array of 10 zeros)

```python
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 5. Creeu una matriu unidimensional de 10 uns (Create a 1D array of 10 ones)

```python
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 6. Creeu una matriu de 3 enters aleatoris entre 1 i 10 (Create a 1D array of 3 random integers between 1 and 10)

```python
array([7, 2, 5])
```

In [6]:
np.random.randint(1, 11, 3)

array([2, 5, 2])

#### 7. Crea una matriu espaiada linealment (Create a 1D array of evenly spaced numbers between 0 and 10)

```python
array([ 0.,  2.,  4.,  6.,  8., 10.])
```

Pista: `np.linspace`

In [7]:
np.linspace(0, 11, 6, dtype=int)

array([ 0,  2,  4,  6,  8, 11])

#### 8. Creeu una matriu de 2 dimensions. Podeu triar els valors (Create a 2D array. You can choose the values)

```python
array([[1, 2, 3],
       [4, 5, 6]])
```


In [8]:
lista1 = list(range(1,5))

np.array([lista1, lista1])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

#### 9. Creeu una matriu de 3x4 amb valors entre 0 i 1. (Create a 3x4 array with values between 0 and 1)

```python
array([[0.14285714, 0.14285714, 0.28571429, 0.42857143],
       [0.57142857, 0.71428571, 0.85714286, 0.85714286],
       [0.14285714, 0.28571429, 0.42857143, 0.57142857]])
```

In [9]:
np.random.random((3, 4))*24

array([[21.84932896,  4.89180723,  6.21516402, 16.61086669],
       [ 0.12202519,  9.8181129 , 21.9670284 , 22.65392238],
       [23.74437657,  8.70915139,  3.83355706, 23.5661106 ]])

#### 10. Creeu una matriu 2D de nombres enters aleatoris. (Create a 2D array of random integers)

```python
array([[7, 9, 2, 5],
       [5, 2, 0, 8],
       [1, 6, 8, 3]])
```
Pista: `np.random.randint`

In [10]:
dosdim = np.random.randint(0, 11,(3,4))

#### 11. Creeu una matriu 1D i afegiu-hi un valor. (Create a 1D array and append a value to it)

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1])
```
Pista: `np.append`

In [11]:
lista2 = [1, 2, 3]
lista3 = [4, 5 ,6]
# no se pueden mezclar más de dos listas
lista_x = np.append(lista3, lista2)

np.append(lista_x, lista1)

array([4, 5, 6, 1, 2, 3, 1, 2, 3, 4])

#### 12. Imprimeix la forma i el nombre de dimensions d'una matriu 1D i 2D. (Print the shape and number of dimensions of a 1D and 2D array)

```python
(10,)
1
(3, 4)
2
```
Pista: `np.shape` i `np.ndim`

In [12]:
lista_x.shape
lista_x.ndim

dosdim.shape
dosdim.ndim

2

#### 13. Compteu el nombre d'elements de les matrius 1D i 2D (Count the number of elements of the 1D and 2D arrays)

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
10
array([[1, 2, 3],
       [4, 5, 6]])
6
```

In [13]:
dosdim = np.random.randint(0, 11,(3,4))

dosdim.size

lista_x.size

6

#### 14. Aconsegueix el primer element d'una matriu 1D i 2D, accedint primer a la matriu "des del davant" i després accedint-hi "des del darrere". (Get the first element of a 1D and 2D array, accessing the array first "starting at the beggining" and then accessing it "starting at the end")

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
0
array([[1, 2, 3],
       [4, 5, 6]])
1

Pista: índex negatiu

In [14]:
lista_x[0]

4

In [15]:
dosdim[0,0]


1

#### 15. Aconsegueix l'últim element d'una matriu 1D i 2D, accedint primer a la matriu des del davant i després accedint-hi des del darrere. (Get the last element of a 1D and 2D array, accessing the array first "starting at the beggining" and then accessing it "starting at the end")

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
9
array([[1, 2, 3],
       [4, 5, 6]])
6
```


In [16]:
dosdim[-1,-1]

10

In [17]:
lista_x[-1]

3

#### 16. Obteniu la primera fila d'una matriu 2D (Get the first row of a 2D array)

```python
array([[1, 2, 3],
       [4, 5, 6]])
       
>> array([1, 2, 3])
````


In [18]:
dosdim[0]

array([1, 2, 5, 5])

#### 17. Obteniu la segona columna d'una matriu 2D (Get the second column of a 2D array)

```python
# Exemple
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

>> array([2, 5, 8])
```

In [19]:
dosdim

array([[ 1,  2,  5,  5],
       [ 0,  9,  8, 10],
       [ 8,  2,  0, 10]])

In [20]:
dosdim[:,1]

array([2, 9, 2])

#### Ara considereu la següent matriu d'enters de l'1 al 10, que farem servir per als exercicis següents. (Now consider the following array of integers from 1 to 10, which we will use for the following exercises.)


In [21]:
v = np.array([ 1,  2,  3,  4 , 5,  6,  7,  8, 9, 10 ])

#### 18. Obteniu els dos primers elements de X. (Get the first two elements of X)

```python
array([1, 2])
```

In [22]:
v[0:2]

array([1, 2])

#### 19. Obteniu els números 3,4 i 5 de X. (Get the numbers 3,4 and 5 from X)

```python
array([3, 4, 5])
```

In [23]:
v[2:5]

array([3, 4, 5])

#### 20. Obteniu els nombres senars. (Get the odd numbers)

```python
array([1, 3, 5, 7, 9])
```

In [24]:
v[[0, 2, 4, 6, 8]]

array([1, 3, 5, 7, 9])

In [25]:
v[0::2]

array([1, 3, 5, 7, 9])

#### 21. Obteniu els nombres parells. (Get the even numbers)

```python
array([ 2,  4,  6,  8, 10])
```


In [26]:
v[1::2]

array([ 2,  4,  6,  8, 10])

#### Ara considereu la següent matriu 2D. (Now consider the following 2D array)

In [27]:
X = np.array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

#### 22. Aconsegueix la primera i la segona fila. (Get the first and second row)

```python

array([[1, 2, 3],
       [4, 5, 6]])
```


In [28]:
X[:2]

array([[1, 2, 3],
       [4, 5, 6]])

#### 23. Obteniu la segona i la tercera columna. (Get the second and third column)

```python
array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])
```

In [29]:
X[:,1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

#### 24. Obteniu l'element 5 i 6. (Get the element 5 and 6)

```python
array([5, 6])
```


In [30]:
X[1,1:]

array([5, 6])

## Funcions universals (Universal functions)

Ara analitzarem algunes funcions que permeten un càlcul ràpid en matrius NumPy. Utilitzarem la mateixa matriu `X` creada abans. (Now we will analyze some functions that allow a quick calculation in NumPy arrays. We will use the same matrix `X` created before.)



In [31]:
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### 25. Troba l'element màxim de X, l'element mínim i la suma de tots els elements de X. (Find the maximum element of X, the minimum element and the sum of all the elements of X.)

```python
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

>> 12
>> 1
>> 78
```


Pista: `np.max`, `np.min` i `np.sum`

In [32]:
np.max(X) #para toda la matriz
np.max(X, axis=0) # para toda la columna
np.max(X, axis=1) #para toda la fila

array([ 3,  6,  9, 12])

In [33]:
import numpy as np

np.max(X, axis=0)

array([10, 11, 12])

In [34]:
import numpy as np


np.min(X)

1

In [35]:
np.sum(X)

78

#### 26. Obteniu la mitjana i la mediana dels valors de X. (Get the mean and median of the values of X.)

```python

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

>> 6.5
>> 6.5
```

Pista: `np.mean` i `np.median`


In [36]:
np.mean(X)

6.5

In [37]:
np.median(X)

6.5

#### 27. Obteniu la quarta potència de cada valor de X. (Get the fourth power of each value of X.)

```python
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

>> array([[    1,    16,    81],
          [  256,   625,  1296],
          [ 2401,  4096,  6561],
          [10000, 14641, 20736]])
```

Pista: `np.power`

In [38]:
import numpy as np 
X = np.array ([[1, 2, 3],
               [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

cuarta_potencia_x = np.power(X, 4)
print(cuarta_potencia_x)

#primero se define la matrix X con la función "np.array()", luego se usa la función "np.power()" para elevar cada elemento de la matriz X a 4. Por lo que pasamos X y
#4 como argumentos a la función "np.power()". Eso devuelve una nueva matriz en la que cada valor de la matriz se eleva a 4.

np.power (X,  [2, 4, 8])
#en este caso es la primera columna elevado a 2, la segunda a 4 y la tercera a 8

[[    1    16    81]
 [  256   625  1296]
 [ 2401  4096  6561]
 [10000 14641 20736]]


array([[        1,        16,      6561],
       [       16,       625,   1679616],
       [       49,      4096,  43046721],
       [      100,     14641, 429981696]])

#### 28. Obteniu el sinus de X

```python

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])
```

Pista: `np.sin`

In [39]:
import numpy as np

X = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9],
              [10, 11, 12]])

seno_X = np.sin(X)

print(seno_X)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292]]


#### 29. Multiplica el cosinus de X per el sinus de X. (Multiply the cosine of X by the sine of X.)

```python

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])


>> array([[ 0.45464871, -0.37840125, -0.13970775],
       [ 0.49467912, -0.27201056, -0.26828646],
       [ 0.49530368, -0.14395166, -0.37549362],
       [ 0.45647263, -0.00442565, -0.45278918]])

```

Pista: `np.cos`

In [40]:
cos_X = np.cos(X)
sin_X = np.sin(X)

mult_cos_sin = cos_X * sin_X

print(mult_cos_sin)

[[ 0.45464871 -0.37840125 -0.13970775]
 [ 0.49467912 -0.27201056 -0.26828646]
 [ 0.49530368 -0.14395166 -0.37549362]
 [ 0.45647263 -0.00442565 -0.45278918]]


#### 30. Obteniu la tangent de X (Get the tangent of X)

```python

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01],
       [ 8.71447983e-01, -6.79971146e+00, -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01]])
```

Pista: `np.tan`

In [41]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01],
       [ 8.71447983e-01, -6.79971146e+00, -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01]])

#### Ara considereu la seguent matriu 2D. (Now consider the following 2D array):

In [42]:
Y= np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 31. Multiplica Y per 2 (Multiply Y by 2)

```python
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])
```

In [43]:
Y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Y *= 2
print(Y)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


#### 32. Divideix `Y` en 3 submatrius de 1x3 (Split `Y` into 3 submatrices of 1x3)

```python
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

>> array([[1, 2, 3]])
>> array([[4, 5, 6]])
>> array([[7, 8, 9]])
```


Pista: `np.split`

In [44]:
import numpy as np
Y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

submatrices = np.split(Y, 3, axis=0)

for sub in submatrices:
    print(sub)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


#### 33. Divideix `Y` en 3 submatrius de 3x1 (Split `Y` into 3 submatrices of 3x1)

```python
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

>> array([[1],
          [4],
          [7]])

>> array([[2],
          [5],
          [8]])

>> array([[3],
          [6],
          [9]])
```


In [45]:
np.split(Y, 3, axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

#### 34. Afegeix 5 a cada element de `Y` (Add 5 to each element of `Y`)

```python
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

>> array([[ 6,  7,  8],
          [ 9, 10, 11],
          [12, 13, 14]])
```
Pista: `np.add`

In [46]:
np.add(X, 5) # es lo mismo que hacer X + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

#### Ara considereu la matriu Z següent (Now consider the following matrix Z):


In [47]:
Z = np.arange(3)[:, np.newaxis]
Z

array([[0],
       [1],
       [2]])

In [48]:
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 35. Multiplica Y i Z (Multiply Y and Z)

```python
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[0],
       [1],
       [2]])

>> array([[ 0,  0,  0],
          [ 4,  5,  6],
          [14, 16, 18]])
```

Pista: `np.multiply`

In [49]:
np.multiply(Y, Z)
#Y * Z

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

## Ordenació, comparació i emmascarament

#### 36. Creeu una matriu de 10 elements enters entre 1 i 5 aleatoris i anomeneu-la X (Create a 10 element array of random integers between 1 and 5 and call it X)

```python
>> array([3, 5, 2, 1, 2, 1, 1, 5, 5, 3])
```

In [50]:
X = np.random.randint(low=1, high=6, size=10)
print(X)

[3 2 1 1 5 3 2 3 4 4]


In [51]:
np.random.randint(1, 6, 10)

array([5, 3, 1, 2, 3, 5, 1, 4, 3, 4])

#### 37. Creeu una matriu de mida (3,3) amb elements aleatoris d'1 a 5 i anomeneu-la Y (Create a (3,3) array of random integers between 1 and 5 and call it Y)

```python
>> array([[1, 2, 1],
          [1, 4, 3],
          [1, 1, 5]])
```

In [52]:
Y = np.random.randint(1,6, (3,3))
print(Y)

[[2 5 2]
 [5 5 4]
 [3 3 2]]


#### 38. Ordena els elements en X de menor a major (Sort the elements in X)

```python
>> array([1, 1, 1, 1, 1, 2, 3, 4, 5])
```

Pista: `np.sort`

In [53]:
np.sort(X) 
#para ordenarlo de mayor a menor es X[np.argsort(-X)]


array([1, 1, 2, 2, 3, 3, 3, 4, 4, 5])

#### 39. Ordena els valors de Y al llarg de l'eix x (files) (Sort the values in Y along the x axis (rows))

```python

array([[1, 2, 1],
       [1, 4, 3],
       [1, 1, 5]])

array([[1, 1, 2],
       [1, 3, 4],
       [1, 1, 5]])
```

Pista: `np.sort`

In [54]:
Y
np.sort(Y, axis= 1)


array([[2, 2, 5],
       [4, 5, 5],
       [2, 3, 3]])

#### 39. Ordena els valors de Y al llarg de l'eix y (columnes) (Sort the values in Y along the y axis (columns))

```python

array([[1, 2, 1],
       [1, 4, 3],
       [1, 1, 5]])

>>> array([[1, 1, 1],
           [1, 2, 3],
           [1, 4, 5]])

In [55]:
np.sort(Y, axis= 0)

array([[2, 3, 2],
       [3, 5, 2],
       [5, 5, 4]])

#### 40. Utilitzeu la funció d'emmascarament (masking) per obtenir els valors de X superiors a 3. (Use the masking function to get the values in X higher than 3)

```python
array([3, 5, 2, 1, 2, 1, 1, 5, 5, 3])

>> array([5, 5, 5])
```


Suggeriment: `x = 8` retornarà una màscara booleana dels valors iguals a 8

In [56]:
value = 9

value > 3

True

In [57]:
X > 3

array([False, False, False, False,  True, False, False, False,  True,
        True])

#### 41. Utilitzeu la funció d'emmascarament per obtenir els valors de X superiors a 1 però inferiors o iguals a 3 (Use the masking function to get the values in X higher than 1 but lower or equal to 3)

```python
array([3, 5, 2, 1, 2, 1, 1, 5, 5, 3])

>> array([3, 2, 2, 1, 1, 1, 3])
```


In [58]:
(X > 1) & (X <= 3)
#para que lo lea de la manera correcta hay que ponerlo entre paréntesis. El and dentro de numpy se representa de manera diferente (&)

array([ True,  True, False, False, False,  True,  True,  True, False,
       False])

In [59]:
X

array([3, 2, 1, 1, 5, 3, 2, 3, 4, 4])

In [60]:
X[np.ma.masked_less_equal(X, 1).mask]

array([1, 1])

In [61]:
X[(np.ma.masked_less_equal(X, 1) & np.ma.masked_greater(X, 3)).mask]

array([1, 1, 5, 4, 4])

    and -> &
    or -> |
    not -> ~
    not equal -> !=
    equal -> ==
    greater than -> >
    less than -> <
    greater or equal -> >=
    less or equal -> <=


In [62]:
np.where(X !=2, 0, X)

array([0, 2, 0, 0, 0, 0, 2, 0, 0, 0])

#### 42. Utilitzeu la funció d'emmascarament per obtenir els valors de X que siguin parells (Use the masking function to get the even values in X)

```python
array([3, 5, 2, 1, 2, 1, 1, 5, 5, 3])

>> array([2, 2])
```


In [63]:
X 

array([3, 2, 1, 1, 5, 3, 2, 3, 4, 4])

In [64]:
is_even = (X%2) == 0
X  [is_even]

array([2, 2, 4, 4])

#### 43. Utilitzeu la funció d'emmascarament per obtenir els valors de X que són imparells (Use the masking function to get the odd values in X)

```python
array([3, 5, 2, 1, 2, 1, 1, 5, 5, 3])

>> array([3, 5, 1, 1, 5, 5, 3])
```

In [65]:
is_odd = (X%2) != 0
X[is_odd]

array([3, 1, 1, 5, 3, 3])

#### 44. Reforma X en una matriu en forma de (2, 5). (Reshape X into a matrix of shape (2, 5))
    
```python
array([3, 5, 2, 1, 2, 1, 1, 5, 5, 3])

>> array([[3, 5, 2, 1, 2],
          [1, 1, 5, 5, 3]])
```

Pista: `np.reshape`

In [66]:
X

array([3, 2, 1, 1, 5, 3, 2, 3, 4, 4])

In [67]:
np.reshape(X, (2,5))

array([[3, 2, 1, 1, 5],
       [3, 2, 3, 4, 4]])

In [68]:
reshaped_X = X.reshape((2,5))
reshaped_X

array([[3, 2, 1, 1, 5],
       [3, 2, 3, 4, 4]])

#### 45. Reforma X en una matriu en forma de (5, 2). (Reshape X into a (5, 2) array)

```python

array([3, 5, 2, 1, 2, 1, 1, 5, 5, 3])

>> array([[3, 5],
          [2, 1],
          [2, 1],
          [1, 5],
          [5, 3]])
```


In [69]:
X

array([3, 2, 1, 1, 5, 3, 2, 3, 4, 4])

In [70]:
reshaped_X.T

array([[3, 3],
       [2, 2],
       [1, 3],
       [1, 4],
       [5, 4]])

In [71]:
X.reshape((5,2))

array([[3, 2],
       [1, 1],
       [5, 3],
       [2, 3],
       [4, 4]])

#### 46. Transposa Z. (Transpose Z)

```python
array([[0],
       [1],
       [2]])

>> array([[0, 1, 2]])

```




In [72]:
Z

array([[0],
       [1],
       [2]])

In [73]:
Z.T

array([[0, 1, 2]])

In [74]:
np.transpose(Z)

array([[0, 1, 2]])

#### 47. Substituïu tots els nombres senars de X per -1 sense canviar X (Replace all odd numbers in X with -1 without changing X)

```python
array([3, 5, 2, 1, 2, 1, 1, 5, 5, 3])

>> array([-1, -1,  2, -1,  2, -1, -1, -1, -1, -1])
```

Pista: np.where

In [75]:
np.where((X%2)==1, -1, X) 

array([-1,  2, -1, -1, -1, -1,  2, -1,  4,  4])

#### 48. Obteniu els elements comuns entre a i b (Get the common items between a and b)

```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

>> array([2 4])
```
Pista: `np.intersect1d`

In [76]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

#### 49. De la matriu a elimina tots els elements presents a la matriu b. (From array a remove all items present in array b)

```python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

>> array([1 2 3 4])
```
Pista: `np.setdiff1d`

In [77]:
result =[]
for element in a:
    if element in b:
        result.append(element)
print(result)

[2, 2, 4, 4]


In [78]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

#### 50. Obteniu les posicions on coincideixen els elements de a i b (Get the positions where elements of a and b match)

```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

>> array([1, 3, 5, 7])
```
Pista: `np.where`

In [79]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)